Update alias and simplify paper gradle-kts markdown
devcordde/tags pull request #23
Opened 2023-08-05 20:40 UTC by rainbowdashlabs

The paper-gradle-kts.md file was updated to include two additional aliases: "paper-gradle" and "minecraft-gradle". The Gradle code snippet was also removed and replace with instructional content, directing users to a blog post for a step-by-step guide on using Gradle in Minecraft. The change was made to provide more comprehensive, user-friendly guide to beginners using Gradle.

2023-08-05 21:50 UTC, Amejonah1200 requested changes
No link to the test-plugin of PaperMC.

2023-08-05 22:15 UTC, rainbowdashlabs commented
> No link to the test-plugin of PaperMC.

The whole point of this blog is to not just throw something at the user which is ready to use, but to explain them every step we make. Thats also the reason why the blog does not contain a full build file.
If we just throw something production ready at them again, they will start using it without thinking and we can explain a bunch of questions again.

2023-08-05 22:20 UTC, Amejonah1200 commented
Ok, then let's do 1 tag but with many aliases, and that tag will feature a bullet point list of what will be learned in that post.

2023-08-05 22:29 UTC, dlsf commented
I also somewhat prefer the current version. We could just add comments to the example build config

2023-08-05 22:46 UTC, rainbowdashlabs commented
> I also somewhat prefer the current version. We could just add comments to the example build config

Current version as the current live version or the current version in this pr?

I would suggest if we really still wanna have the default template, which still misses the plugin.yml and runServer or copyToServer to move it into a haste link. posting so much code isnt what we want as well from users, so we should keep it out of our tags as well.

2023-08-05 22:50 UTC, rainbowdashlabs commented
> Ok, then let's do 1 tag but with many aliases, and that tag will feature a bullet point list of what will be learned in that post.

It might be helpful in a lot of cases to directly point at a specific section with a description what can be expected from this section and why it is important.

2023-08-05 23:38 UTC, Amejonah1200 commented
> > Ok, then let's do 1 tag but with many aliases, and that tag will feature a bullet point list of what will be learned in that post.
> 
> It might be helpful in a lot of cases to directly point at a specific section with a description what can be expected from this section and why it is important.

Well then, a list with links instead. Because now we need to manage 4 (afaik) different tags with little to no information with just a link to your blog post...

2023-08-06 08:22 UTC, yannicklamprecht submitted a review, later dismissed

2023-08-06 08:42 UTC, rainbowdashlabs commented
> Well then, a list with links instead. Because now we need to manage 4 (afaik) different tags with little to no information with just a link to your blog post...

How is this better? The tags have "little to no information" because they source of truth is contained in the link. That is also the reason why we wont need to update the tags. There is just nothing that can become outdated.

A list with links would still require a description and explanation why they should klick on it, so we would effectivly end up copying all tags into one tag and people need to read the full tag to find what they are looking for. In which way would that be an improvement in user experience? We would post links which do not all match the users expectation, end up with an confused user and win nothing.

There is nothing bad in having small tags dedicated to a single topic.

2023-08-06 10:15 UTC, DerTev submitted a review, later dismissed

2023-08-06 10:15 UTC, kxmpxtxnt approved these changes, later dismissed

2023-08-06 10:34 UTC, Amejonah1200 commented
The initial idea of this tag was to have a copy-ready snippet for creating a working build.gradle.kts file. Just providing a link to your blog misses the point, it would be better to remove the `paper-gradle-kts` alias then, and add more information of what the blog post have to offer on the creation of plugins for paper using Gradle.

Additionally, there are people out there who just need the coordinates for paper, as they may know about Gradle already and working with spigot before, not a whole blog post.

2023-08-06 13:36 UTC, rainbowdashlabs commented
> The initial idea of this tag was to have a copy-ready snippet for creating a working build.gradle.kts file. Just providing a link to your blog misses the point, it would be better to remove the paper-gradle-kts alias then, and add more information of what the blog post have to offer on the creation of plugins for paper using Gradle.

Like I said, we can still add a link with a paste to the tag

2023-08-06 13:43 UTC, Amejonah1200 commented
> Like I said, we can still add a link with a paste to the tag

Please do

2023-08-06 14:06 UTC, rainbowdashlabs commented
I created a new one and didn't took the old one, but it contains everything important

2023-08-06 14:09 UTC, kxmpxtxnt submitted a review, later dismissed

2023-08-06 14:21 UTC, Amejonah1200 commented on minecraft/paper-gradle-kts.md
> +Wenn du einfach nur auf der suche nach einer schnellen Referenz bist, schau [hier](<https://haste.devcord.club/orizodomar.java>)
Or better: upload it on this repo or as a gist.

2023-08-06 14:33 UTC, Amejonah1200 commented
settings.gradle.kts?
https://raw.githubusercontent.com/PaperMC/paperweight-test-plugin/master/settings.gradle.kts ?

2023-08-06 14:36 UTC, Amejonah1200 approved these changes

2023-08-06 15:41 UTC, dlsf approved these changes

2023-08-06 15:41 UTC, merged