Update major-versions.md
devcordde/tags pull request #41
Opened 2024-03-26 14:47 UTC by dlsf

Habe die Tabelle ein wenig schöner gemacht, die neuen Classversions hinzugefügt und Java 6 + 7 entfernt, weil sie nicht mehr relevant sein sollten. Wir können die horizontalen Striche gerne wieder reinmachen, aber ich finde es so fast besser

![image](https://github.com/devcordde/tags/assets/35780068/59b08957-4dd3-4578-b10d-88fd2babee5c)

![image](https://github.com/devcordde/tags/assets/35780068/c9afe76c-93b3-4b34-889a-587ec651717c)

2024-03-26 14:51 UTC, rainbowdashlabs requested changes
In discord ist das ziemlich broken mit dem spacing derzeit.

![image](https://github.com/devcordde/tags/assets/46890129/fc477f13-9550-4dba-b84e-be85c5fee98b)

Eventuell könnte man außerdem noch die LTS oder zumindest derzeitige LTS markieren?

2024-03-26 15:19 UTC, dlsf commented
Habe genau das selbe mit /preview modal probiert und es sah wie in meinem Screenshot aus. Markieren geht leider nicht so wirklich, weil es ein Codeblock ist. Wir könnten höchstens LTS dahinterschreiben?

2024-03-26 15:28 UTC, rainbowdashlabs commented
Ist mir ein rätsel, was du da rein gepastet hast. Würde immer die url zum file nehmen von github.

![image](https://github.com/devcordde/tags/assets/46890129/4179a85d-9e78-4c85-a489-21623d9f98c4)

Sowohl github code als auch discord code blocks haben monofont. wenn das also schon hier nicht alligned wird das in discord auch nicht alligned sein.

Vorher was das hier ja auch bei monofont wunderbar alligned.

2024-03-26 15:31 UTC, yannicklamprecht commented
Warum eigentlich als Textblock? Markdown kann Tabellen.

2024-03-26 16:13 UTC, rainbowdashlabs commented on java/major-versions.md
> +└──────────────┴────────────────┘
Vorschlag. Würde LTS doch raus lassen. Das verwirrt nur unnötig und suggeriert, dass man diese Version statt einer neueren nutzen sollte.
```
┌──────────────┬───────────────┐
│ Java Version │ Major Version │
╞══════════════╪═══════════════╡
│    Java 8    │      52       │
│    Java 9    │      53       │
│   Java 10    │      54       │
│   Java 11    │      55       │
│   Java 12    │      56       │
│   Java 13    │      57       │
│   Java 14    │      58       │
│   Java 15    │      59       │
│   Java 16    │      60       │
│   Java 17    │      61       │
│   Java 18    │      62       │
│   Java 19    │      63       │
│   Java 20    │      64       │
│   Java 21    │      65       │
│   Java 22    │      66       │
└──────────────┴───────────────┘
```

2024-03-26 16:19 UTC, dlsf commented
@rainbowdashlabs Und mir ist ein Rätsel, was du dort reingepasted hast. `/preview url https://raw.githubusercontent.com/devcordde/tags/major-versions-java-22/java/major-versions.md` funktioniert ohne Probleme

@yannicklamprecht Ich glaube nicht, dass Discord Markdown-Tabellen unterstützt?

2024-03-26 16:34 UTC, rainbowdashlabs commented
@dlsf  Bei mir lustigerweise nicht. 
![image](https://github.com/devcordde/tags/assets/46890129/c6689d7a-ffd7-452e-bf42-b2d51f6d3ae2)
Und nein discord unterstützt keine markdown tabellen

2024-03-26 16:55 UTC, yannicklamprecht commented
@rainbowdashlabs so siehts bei mir mit dem link von @dlsf auch aus.

Schade, dass DC Markdown nicht vollständig unterstützt.

2024-03-30 14:44 UTC, Goldmensch reviewed
Ich würde Java 8/9 um ein Leerzeichen ergänzen, damit "Java" in allen Zeilen aligned ist.

2024-03-31 07:13 UTC, rainbowdashlabs commented
Hab meinen vorschlag mal angepasst. Den könnte man dann so nehmen.
Preview Desktop
![grafik](https://github.com/devcordde/tags/assets/46890129/ea4d88f6-e06c-489e-a20e-33c3e017b5d6)
Preview Mobile
![Screenshot_20240331-091208](https://github.com/devcordde/tags/assets/46890129/f85caf84-34a0-41fb-a590-356b8884aadf)

2024-04-04 12:58 UTC, rainbowdashlabs commented
Ich war mal so frei, damit wir hier weiter kommen c:

2024-04-04 12:59 UTC, rainbowdashlabs approved these changes

2024-04-04 13:02 UTC, Goldmensch approved these changes

2024-04-04 13:02 UTC, merged