Outdated Java Download Link
devcordde/tags pull request #7
Opened 2023-07-31 23:23 UTC by richardwhateverr

2023-07-31 23:59 UTC, dlsf requested changes

2023-07-31 23:59 UTC, dlsf commented on minecraft/bievieh-mc-tutorial.md
> +Java Version: https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.8%2B7/OpenJDK17U-jdk_x64_windows_hotspot_17.0.8_7.msi
This shouldn't be a Windows-specific link

2023-08-01 00:15 UTC, dlsf approved these changes

2023-08-01 10:19 UTC, NyCodeGHG approved these changes

2023-08-01 10:29 UTC, merged